// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sistemaWeb_ventasOnline;

#nullable disable

namespace sistemaWeb_ventasOnline.Migrations
{
    [DbContext(typeof(AplicacionDBContext))]
    partial class AplicacionDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("sistemaWeb_ventasOnline.Entidades.Categoria", b =>
                {
                    b.Property<int>("idCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idCategoria"));

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idCategoria");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("sistemaWeb_ventasOnline.Entidades.Cupon", b =>
                {
                    b.Property<int>("idCupon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idCupon"));

                    b.Property<string>("codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("descuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("fechaExpiracion")
                        .HasColumnType("datetime2");

                    b.Property<int>("usoMaximo")
                        .HasColumnType("int");

                    b.Property<int>("usosActuales")
                        .HasColumnType("int");

                    b.HasKey("idCupon");

                    b.ToTable("Cupon");
                });

            modelBuilder.Entity("sistemaWeb_ventasOnline.Entidades.Detalle", b =>
                {
                    b.Property<int>("idDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idDetalle"));

                    b.Property<int>("cantidad")
                        .HasColumnType("int");

                    b.Property<int>("idProducto")
                        .HasColumnType("int");

                    b.Property<decimal>("precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("idDetalle");

                    b.HasIndex("idProducto");

                    b.ToTable("Detalle");
                });

            modelBuilder.Entity("sistemaWeb_ventasOnline.Entidades.Orden", b =>
                {
                    b.Property<int>("idOrden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idOrden"));

                    b.Property<DateTime>("fechaOrden")
                        .HasColumnType("datetime2");

                    b.Property<int>("idCupon")
                        .HasColumnType("int");

                    b.Property<int>("idDetalle")
                        .HasColumnType("int");

                    b.Property<int>("idUsuario")
                        .HasColumnType("int");

                    b.Property<decimal>("total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("idOrden");

                    b.HasIndex("idCupon");

                    b.HasIndex("idDetalle");

                    b.HasIndex("idUsuario");

                    b.ToTable("Orden");
                });

            modelBuilder.Entity("sistemaWeb_ventasOnline.Entidades.Producto", b =>
                {
                    b.Property<int>("idProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idProducto"));

                    b.Property<int>("cantidad")
                        .HasColumnType("int");

                    b.Property<int>("idCategoria")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("idProducto");

                    b.HasIndex("idCategoria");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("sistemaWeb_ventasOnline.Entidades.Usuario", b =>
                {
                    b.Property<int>("idUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idUsuario"));

                    b.Property<string>("contraseña")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idUsuario");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("sistemaWeb_ventasOnline.Entidades.Detalle", b =>
                {
                    b.HasOne("sistemaWeb_ventasOnline.Entidades.Producto", "Producto")
                        .WithMany("Detalle")
                        .HasForeignKey("idProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("sistemaWeb_ventasOnline.Entidades.Orden", b =>
                {
                    b.HasOne("sistemaWeb_ventasOnline.Entidades.Cupon", "Cupon")
                        .WithMany("Orden")
                        .HasForeignKey("idCupon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sistemaWeb_ventasOnline.Entidades.Detalle", "Detalle")
                        .WithMany("Orden")
                        .HasForeignKey("idDetalle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sistemaWeb_ventasOnline.Entidades.Usuario", "Usuario")
                        .WithMany("Orden")
                        .HasForeignKey("idUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cupon");

                    b.Navigation("Detalle");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("sistemaWeb_ventasOnline.Entidades.Producto", b =>
                {
                    b.HasOne("sistemaWeb_ventasOnline.Entidades.Categoria", "Categoria")
                        .WithMany("Producto")
                        .HasForeignKey("idCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("sistemaWeb_ventasOnline.Entidades.Categoria", b =>
                {
                    b.Navigation("Producto");
                });

            modelBuilder.Entity("sistemaWeb_ventasOnline.Entidades.Cupon", b =>
                {
                    b.Navigation("Orden");
                });

            modelBuilder.Entity("sistemaWeb_ventasOnline.Entidades.Detalle", b =>
                {
                    b.Navigation("Orden");
                });

            modelBuilder.Entity("sistemaWeb_ventasOnline.Entidades.Producto", b =>
                {
                    b.Navigation("Detalle");
                });

            modelBuilder.Entity("sistemaWeb_ventasOnline.Entidades.Usuario", b =>
                {
                    b.Navigation("Orden");
                });
#pragma warning restore 612, 618
        }
    }
}
